# Generated by Django 5.0.7 on 2024-09-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
