# Generated by Django 5.0.7 on 2024-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_contact_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_not_read',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
