# Generated by Django 5.0.7 on 2024-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='текущая версия'),
        ),
    ]
