# Generated by Django 5.0.7 on 2024-10-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_edit_description', 'может редактировать описание'), ('can_edit_category', 'может редактировать категорию'), ('can_published', 'может публиковать продукт')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
